-- ============================================================================
-- TRX_EVENT_MAP : 이벤트(액션)별 적용 FAB 매핑
--
--   ※ 이 테이블은 레이어별로 복제되는 BIZ_AIACTIONTXN_HIS 와 다르다.
--     이 앱의 "자체 DB"(= GAIA DB) 에만 단 한 번 생성한다.
--     (코드: src/lib/config.ts 의 EVENT_FAB_DB_LAYER = APP_DB_LAYER = GAIA)
--   ※ TRX_TOKEN_DET 와 동일하게 앱 접속 계정으로 그냥 생성하면 된다.
--     (GRANT / PUBLIC SYNONYM 불필요 — 과거 MCP DB 시절 산출물이 남아 있다면
--      아래 [기존 MCP DB 객체 정리] 를 MCP DB 에서 먼저 실행)
--
--   용도 : 하이닉스는 기능(이벤트)을 FAB 별로 선별 적용한다.
--          예) AutoQual 실행(AUTOQUAL_BM)은 M14/M15 두 팹에서만 사용.
--          TraceX "/event-fabs" 화면에서 이벤트별 허용 FAB 을 편집하면
--          이 테이블에 저장되고, 판정 로직은 요청의 FAB 이 허용 목록에 없으면 팅겨낸다.
--          FAB 종류: C2 / M10 / M11 / M14 / M15 / M16 / Y17
--
--   행 단위 : 이벤트 1개 × 허용 FAB 1개 = 1행 (M14/M15 허용이면 2행).
--   저장 방식: TraceX 앱이 이 테이블의 마스터 — 저장 시 전량 교체(DELETE 후 INSERT).
--             수동으로 넣은 행도 다음 저장 때 앱 화면 상태로 덮어써진다.
--   판정 규칙: EVENT_ID 의 USE_YN='Y' 행들의 FAB_ID 집합 = 허용 FAB.
--             매핑이 한 건도 없는 이벤트의 처리(전 FAB 허용 or 차단)는 판정측 정책으로
--             결정한다 — 아래 [연동 예시] 의 allow_when_unregistered 파라미터.
-- ============================================================================

-- ============================================================================
-- [기존 MCP DB 객체 정리] — 이전 버전을 MCP DB 에 만들었던 경우에만,
--   MCP DB 에서 IDMSADM2 계정으로 실행 (시노님 → 테이블 순)
-- ============================================================================
-- DROP PUBLIC SYNONYM TRX_EVENT_MAP;
-- DROP TABLE IDMSADM2.TRX_EVENT_MAP PURGE;

-- ============================================================================
-- [신규 생성] — GAIA DB(앱 자체 DB) 에서 앱 접속 계정으로 실행
-- ============================================================================
CREATE TABLE TRX_EVENT_MAP (
    MAP_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY,  -- 매핑 행 surrogate key (PK)
    EVENT_ID           VARCHAR2(50)   NOT NULL,                  -- 이벤트(액션) 식별자 — BIZ_AIACTIONTXN_HIS.ACTION_TYP 값과 일치 (ex. SEA/AUTOQUAL_CANCEL/AUTOQUAL_BM)
    FAB_ID             VARCHAR2(20)   NOT NULL,                  -- 허용 FAB (C2/M10/M11/M14/M15/M16/Y17)
    USE_YN             CHAR(1)        DEFAULT 'Y' NOT NULL,      -- 사용 여부 (판정은 'Y' 만 읽음. DB 수동 비활성화용 — 단 앱 저장 시 전량 교체됨)
    REG_DT             TIMESTAMP      DEFAULT SYSTIMESTAMP,      -- 등록 일시
    UPD_DT             TIMESTAMP      DEFAULT SYSTIMESTAMP,      -- 수정 일시
    CONSTRAINT PK_TRX_EVENT_MAP PRIMARY KEY (MAP_ID),
    CONSTRAINT UX_TRX_EVENT_MAP UNIQUE (EVENT_ID, FAB_ID)   -- 이벤트×FAB 중복 방지. 판정 조회(EVENT_ID 선두)도 이 인덱스를 탄다
);

-- 컬럼 코멘트 ---------------------------------------------------------------
COMMENT ON TABLE  TRX_EVENT_MAP          IS '이벤트(액션)별 적용 FAB 매핑 (앱 자체 DB 전용 — TraceX /event-fabs 에서 편집)';
COMMENT ON COLUMN TRX_EVENT_MAP.MAP_ID   IS '매핑 행 surrogate key';
COMMENT ON COLUMN TRX_EVENT_MAP.EVENT_ID IS '이벤트(액션) 식별자 — ACTION_TYP 값 (SEA/AUTOQUAL_CANCEL/AUTOQUAL_BM 등)';
COMMENT ON COLUMN TRX_EVENT_MAP.FAB_ID   IS '허용 FAB (C2/M10/M11/M14/M15/M16/Y17)';
COMMENT ON COLUMN TRX_EVENT_MAP.USE_YN   IS '사용 여부 (Y/N — 판정은 Y 만 읽음)';
COMMENT ON COLUMN TRX_EVENT_MAP.REG_DT   IS '등록 일시';
COMMENT ON COLUMN TRX_EVENT_MAP.UPD_DT   IS '수정 일시';

COMMIT;

-- ============================================================================
-- [확인 쿼리]
-- ============================================================================
-- SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
--   FROM USER_TAB_COLUMNS
--  WHERE TABLE_NAME = 'TRX_EVENT_MAP'
--  ORDER BY COLUMN_ID;

-- 이벤트별 허용 FAB 한눈에 보기:
-- SELECT EVENT_ID, LISTAGG(FAB_ID, ',') WITHIN GROUP (ORDER BY FAB_ID) AS FABS
--   FROM TRX_EVENT_MAP
--  WHERE USE_YN = 'Y'
--  GROUP BY EVENT_ID
--  ORDER BY EVENT_ID;

-- ============================================================================
-- [ROLLBACK] — GAIA DB 에서 실행
-- ============================================================================
-- DROP TABLE TRX_EVENT_MAP PURGE;
-- COMMIT;

/* ============================================================================
   [연동 예시 — Python]

   커넥션/커서 관리는 판정 서버에 이미 있으므로, 여기는 "쿼리 날려서 체크" 하는
   비즈니스 로직만 담았다. GAIA DB 커넥션의 cursor 와 event_id(액션 타입),
   fab_id 를 파라미터로 넘겨 호출하면 된다.

   - allow_when_unregistered:
       True  (기본) = 매핑이 아직 등록되지 않은 이벤트는 전 FAB 허용
       False        = 등록되지 않은 이벤트는 전부 차단

# ----------------------------------------------------------------------------
def is_fab_allowed(cursor, event_id: str, fab_id: str,
                   allow_when_unregistered: bool = True) -> bool:
    """이 이벤트(event_id)를 이 FAB(fab_id)에서 실행해도 되는가.

    사용 예 (요청 처리 진입부):
        if not is_fab_allowed(cursor, action_typ, fab_id):
            raise PermissionError(
                f"'{action_typ}' 는 {fab_id} FAB 에 적용되지 않은 기능입니다.")
    """
    cursor.execute(
        """SELECT FAB_ID
             FROM TRX_EVENT_MAP
            WHERE EVENT_ID = :event_id
              AND USE_YN = 'Y'""",
        {"event_id": event_id.strip()},
    )
    allowed = {row[0].strip().upper() for row in cursor.fetchall()}
    if not allowed:
        return allow_when_unregistered  # 매핑 미등록 이벤트 정책
    return fab_id.strip().upper() in allowed
# ----------------------------------------------------------------------------
============================================================================ */
