-- ============================================================================
-- TRX_EVENT_MAP : 이벤트(액션)별 적용 FAB 매핑
--
--   ※ 이 테이블은 레이어별로 복제되는 BIZ_AIACTIONTXN_HIS 와 다르다.
--     MCP 의 DB 에만 단 한 번 생성한다. (앱 자체 DB = GAIA 가 아님에 주의!)
--     MCP 로직이 요청 FAB 허용 여부를 판정할 때 직접 읽어야 해서 MCP DB 에 둔다.
--     (코드: src/lib/config.ts 의 EVENT_FAB_DB_LAYER, getEventFabDbConfig())
--
--   용도 : 하이닉스는 기능(이벤트)을 FAB 별로 선별 적용한다.
--          예) AutoQual 실행(AUTOQUAL_BM)은 M14/M15 두 팹에서만 사용.
--          TraceX "/event-fabs" 화면에서 이벤트별 허용 FAB 을 체크박스로 편집하면
--          이 테이블에 저장되고, MCP 는 요청의 FAB 이 허용 목록에 없으면 팅겨낸다.
--          FAB 종류: C2 / M10 / M11 / M14 / M15 / M16 / Y17
--
--   행 단위 : 이벤트 1개 × 허용 FAB 1개 = 1행 (M14/M15 허용이면 2행).
--   저장 방식: TraceX 앱이 이 테이블의 마스터 — 저장 시 전량 교체(DELETE 후 INSERT).
--             수동으로 넣은 행도 다음 저장 때 앱 화면 상태로 덮어써진다.
--   판정 규칙: EVENT_ID 의 USE_YN='Y' 행들의 FAB_ID 집합 = 허용 FAB.
--             매핑이 한 건도 없는 이벤트의 처리(전 FAB 허용 or 차단)는 MCP 정책으로
--             결정한다 — 아래 [MCP 연동 예시] 의 allow_when_unregistered 파라미터.
-- ============================================================================

CREATE TABLE TRX_EVENT_MAP (
    MAP_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY,  -- 매핑 행 surrogate key (PK)
    EVENT_ID           VARCHAR2(50)   NOT NULL,                  -- 이벤트(액션) 식별자 — BIZ_AIACTIONTXN_HIS.ACTION_TYP 값과 일치 (ex. SEA/AUTOQUAL_CANCEL/AUTOQUAL_BM)
    FAB_ID             VARCHAR2(20)   NOT NULL,                  -- 허용 FAB (C2/M10/M11/M14/M15/M16/Y17)
    USE_YN             CHAR(1)        DEFAULT 'Y' NOT NULL,      -- 사용 여부 (MCP 는 'Y' 만 읽음. DB 수동 비활성화용 — 단 앱 저장 시 전량 교체됨)
    REG_DT             TIMESTAMP      DEFAULT SYSTIMESTAMP,      -- 등록 일시
    UPD_DT             TIMESTAMP      DEFAULT SYSTIMESTAMP,      -- 수정 일시
    CONSTRAINT PK_TRX_EVENT_MAP PRIMARY KEY (MAP_ID),
    CONSTRAINT UX_TRX_EVENT_MAP UNIQUE (EVENT_ID, FAB_ID)   -- 이벤트×FAB 중복 방지. MCP 조회(EVENT_ID 선두)도 이 인덱스를 탄다
);

-- 컬럼 코멘트 ---------------------------------------------------------------
COMMENT ON TABLE  TRX_EVENT_MAP          IS '이벤트(액션)별 적용 FAB 매핑 (MCP DB 전용 — TraceX /event-fabs 에서 편집)';
COMMENT ON COLUMN TRX_EVENT_MAP.MAP_ID   IS '매핑 행 surrogate key';
COMMENT ON COLUMN TRX_EVENT_MAP.EVENT_ID IS '이벤트(액션) 식별자 — ACTION_TYP 값 (SEA/AUTOQUAL_CANCEL/AUTOQUAL_BM 등)';
COMMENT ON COLUMN TRX_EVENT_MAP.FAB_ID   IS '허용 FAB (C2/M10/M11/M14/M15/M16/Y17)';
COMMENT ON COLUMN TRX_EVENT_MAP.USE_YN   IS '사용 여부 (Y/N — MCP 는 Y 만 읽음)';
COMMENT ON COLUMN TRX_EVENT_MAP.REG_DT   IS '등록 일시';
COMMENT ON COLUMN TRX_EVENT_MAP.UPD_DT   IS '수정 일시';

COMMIT;

-- ============================================================================
-- [확인 쿼리]
-- ============================================================================
-- SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
--   FROM USER_TAB_COLUMNS
--  WHERE TABLE_NAME = 'TRX_EVENT_MAP'
--  ORDER BY COLUMN_ID;

-- 이벤트별 허용 FAB 한눈에 보기:
-- SELECT EVENT_ID, LISTAGG(FAB_ID, ',') WITHIN GROUP (ORDER BY FAB_ID) AS FABS
--   FROM TRX_EVENT_MAP
--  WHERE USE_YN = 'Y'
--  GROUP BY EVENT_ID
--  ORDER BY EVENT_ID;

-- ============================================================================
-- [ROLLBACK]
-- ============================================================================
-- DROP TABLE TRX_EVENT_MAP PURGE;
-- COMMIT;

/* ============================================================================
   [MCP 연동 예시 — Python]

   MCP 서버(Python)에서 요청을 처리하기 전에 아래 메서드로 FAB 허용 여부를
   체크한다. 호출부에서 event_id(액션 타입)와 fab_id 를 파라미터로 넘기면 된다.

   - 매핑은 자주 안 바뀌는 마스터 데이터라 TTL 캐시(기본 5분)를 둔다.
     TraceX 화면에서 저장한 변경은 최대 TTL 만큼 지나야 MCP 에 반영된다.
   - allow_when_unregistered:
       True  (기본) = 매핑이 아직 등록되지 않은 이벤트는 전 FAB 허용
       False        = 등록되지 않은 이벤트는 전부 차단
   - DB 조회 실패 시엔 기능이 통째로 죽지 않도록 '허용' 으로 폴백한다
     (fail-open). 차단이 더 중요하면 except 블록에서 False 를 리턴할 것.

# ----------------------------------------------------------------------------
import time
from typing import Dict, Optional, Set

import oracledb   # pip install oracledb (thin 모드면 Instant Client 불필요)

_CACHE_TTL_SEC = 300  # 매핑 캐시 TTL(초)
_cache = {"at": 0.0, "map": None}  # type: dict


def _load_event_fab_map(conn) -> Dict[str, Set[str]]:
    """TRX_EVENT_MAP 전체를 {EVENT_ID: {FAB_ID, ...}} 로 로드."""
    cur = conn.cursor()
    try:
        cur.execute(
            """SELECT EVENT_ID, FAB_ID
                 FROM TRX_EVENT_MAP
                WHERE USE_YN = 'Y'"""
        )
        result: Dict[str, Set[str]] = {}
        for event_id, fab_id in cur:
            result.setdefault(event_id.strip(), set()).add(fab_id.strip().upper())
        return result
    finally:
        cur.close()


def get_allowed_fabs(conn, event_id: str) -> Optional[Set[str]]:
    """이벤트의 허용 FAB 집합. 매핑 미등록 이벤트면 None."""
    now = time.time()
    if _cache["map"] is None or now - _cache["at"] > _CACHE_TTL_SEC:
        _cache["map"] = _load_event_fab_map(conn)
        _cache["at"] = now
    return _cache["map"].get(event_id.strip())


def is_fab_allowed(conn, event_id: str, fab_id: str,
                   allow_when_unregistered: bool = True) -> bool:
    """이 이벤트를 이 FAB 에서 실행해도 되는가.

    사용 예:
        if not is_fab_allowed(conn, action_typ, fab_id):
            raise PermissionError(
                f"'{action_typ}' 는 {fab_id} FAB 에 적용되지 않은 기능입니다.")
    """
    try:
        allowed = get_allowed_fabs(conn, event_id)
    except Exception:
        return True  # fail-open: 매핑 조회 실패로 기능 전체가 죽지 않게 허용 폴백
    if allowed is None:
        return allow_when_unregistered  # 매핑 미등록 이벤트 정책
    return fab_id.strip().upper() in allowed
# ----------------------------------------------------------------------------
============================================================================ */
